### PR TITLE
#17 implement user sign in

### PR DESCRIPTION
**Pull request by OleksiyRudeyko**
my pull request contains also the changes from branch #6-implement-user-sign-up

### CODE REVIEW

**Review by YanZhylavy — CHANGES_REQUESTED** [review]
Implemented authentication here essentially does the same thing as what was already done in task #5 (set up jwt-authentication), except manually specifying the view that authenticates the user - LoginView (doing the same thing as the ready-made TokenObtainPairView from the restframework_simplejwt library at the 'api/token' endpoint). The only difference is that your view also returns the user's identifier and their email (which is interpreted as the username, which is also a debatable issue). Overall, of course, your work is done, this is more of a task distribution issue.

**Comment by YanZhylavy** [comment]
We should consult with mentors, perhaps they will decide it's better to keep your version and remove my endpoint. However, having two endpoints with similar functionality definitely isn't advisable :)

**Comment by OleksiyRudeyko** [comment]
- token url deleted
- username changed for email in views

**Review by YanZhylavy — APPROVED** [review]

**Review by mehalyna — APPROVED** [review]

**Review by akostromin14 — APPROVED** [review]
Looks great!

**Pull request merged**
